// apps/my-vue-app/src/App.vue
<template>
  <div>
    <h1>Payment Page</h1>
    <bullring-payment-widget
      :merchant-id="merchantId"
      :merchant-name="merchantName"
      :invoice-amount="100" 
      @payment-success="handlePaymentSuccess"
      @payment-error="handlePaymentError"
      @close="handleClose"
    />
  </div>
</template>

<script setup lang="ts">
import '@bullring/payment-widget/dist';
import '@bullring/payment-widget/dist/styles.css';

const merchantId = 'e6095fa1-4d03-4d6b-8fa8-e77009484a6e';
const merchantName = 'Test Store';

const handlePaymentSuccess = (data: any) => {
  console.log('Payment successful:', data);
};

const handlePaymentError = (error: Error) => {
  console.error('Payment failed:', error);
};

const handleClose = (txId: string) => {
  console.log('Widget closed, transaction ID:', txId);
};
</script>

<style>
/* Any styles you need */
</style>

// apps/dev/src/App.tsx
import React, { useState } from "react";
import "./App.css";
import "@bullring/payment-widget";

export interface BullringPaymentWidgetProps
  extends React.DetailedHTMLProps<
    React.HTMLAttributes<HTMLElement>,
    HTMLElement
  > {
  amount: number;
  merchantId: string;
  merchantName?: string;
  onPaymentSuccess?: (data: any) => void;
  onPaymentError?: (error: Error) => void;
  onClose?: (txId: string) => void;
}

function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      {count === 0 ? (
        <button onClick={() => setCount(1)}> Pay 1000 brl</button>
      ) : null}
      {count === 1 ? (
        <bullring-payment-widget
          invoice-amount={1000}
          note="Test payment"
          merchant-id={"e6095fa1-4d03-4d6b-8fa8-e77009484a6e"}
          onpaymentSuccess={(txid) => console.log("Payment received:", txid)}
          onpaymentError={(txid) => console.log("Payment received:", txid)}
          onclose={() => {
            console.log("yey!");
            setCount(0);
          }}
        />
      ) : null}
    </>
  );
}

export default App;
